import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { BootstrapClient } from "@/components/ui";
import { ToastNotifications } from "@/components/ui/ToastNotifications";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Example Next PDF Export",
  description: "Generated by example next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BootstrapClient />
        <ToastNotifications />
        {children}
      </body>
    </html>
  );
}
